# 동작 환경 설정
spring:
  application:
    name: BionLifeScienceWeb
  profiles:
    active: prod
server:
  port: 8080
  servlet:
    session:
      timeout: 1440m      # 60m * 24h * 30d
      cookie:
        max-age: 1440m    # 60m * 24h * 30d
        name: SID
        http-only: true
        secure: true
# 개발 환경
--- 
spring:
  config:
    activate: 
      on-profile: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://183.111.199.216:3306/bionls?useUnicode=true&characterEncoding=utf8
    username: bionls
    password: bion2272!@
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: -1
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'bionlifesci@gmail.com'
    password: 'nuuhdepcsveygwsy'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  upload.path: src/main/resources/static/administration
  upload.env: local

# 배포 환경
--- 
spring:
  config:
    activate: 
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bionls?useUnicode=true&characterEncoding=utf8
    username: bionls
    password: bion2272!@
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: -1
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'bionlifesci@gmail.com'
    password: 'nuuhdepcsveygwsy'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  upload.path: /home/hosting_users/bionls/tomcat/webapps
  upload.env: prod


    
